# Generated by Django 4.2.5 on 2023-09-18 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('UsuarioId', models.AutoField(primary_key=True, serialize=False)),
                ('UsuarioNickName', models.CharField(max_length=30)),
                ('UsuarioEmail', models.CharField(max_length=60)),
                ('UsuarioDataNascimento', models.DateField()),
                ('UsuarioDataCadastro', models.DateField()),
                ('UsuarioFotoPerfil', models.CharField(max_length=100)),
            ],
        ),
    ]
