# Generated by Django 4.2.5 on 2023-09-18 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciaAssunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Assunto_Nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='UsuarioDataCadastro',
            new_name='Usuario_Data_Cadastro',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='UsuarioDataNascimento',
            new_name='Usuario_Data_Nascimento',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='UsuarioEmail',
            new_name='Usuario_Email',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='UsuarioId',
            new_name='Usuario_Id',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='UsuarioNickName',
            new_name='Usuario_Nickname',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='UsuarioFotoPerfil',
        ),
        migrations.AddField(
            model_name='usuario',
            name='Usuario_Descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='Usuario_Foto_Perfil',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='Usuario_Senha',
            field=models.CharField(default=12345, max_length=128),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Seguir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Seguidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidores', to='BlogApp.usuario')),
                ('Seguindo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguindo', to='BlogApp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Postagem_Conteudo', models.TextField()),
                ('Postagem_Data', models.DateTimeField(auto_now_add=True)),
                ('Postagem_Autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogApp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comentario_Texto', models.TextField()),
                ('Comentario_Data', models.DateTimeField(auto_now_add=True)),
                ('Comentario_Autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogApp.usuario')),
                ('Postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogApp.postagem')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='Usuario_Assuntos',
            field=models.ManyToManyField(to='BlogApp.preferenciaassunto'),
        ),
    ]
