# Generated by Django 4.2.5 on 2023-10-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_preferenciaassunto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferenciaassunto',
            name='Assunto_Nome',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Usuario_Email',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Usuario_Nickname',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
