# Generated by Django 4.2.5 on 2023-11-06 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0003_alter_preferenciaassunto_assunto_nome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguir',
            name='Seguidor',
        ),
        migrations.RemoveField(
            model_name='seguir',
            name='Seguindo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='Usuario_Assuntos',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='Usuario_Descricao',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='Usuario_Foto_Perfil',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='PreferenciaAssunto',
        ),
        migrations.DeleteModel(
            name='Seguir',
        ),
    ]
